set -g default-command "${SHELL}"
set -g mouse on
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ",alacritty*:Tc"
bind  c  new-window -c "#{pane_current_path}"

set -sg escape-time 10
set -sg set-clipboard on
set -g focus-events on
set -g prefix M-j
unbind C-b
set -g base-index 1
set -g status off

bind-key -T prefix h select-pane -L
bind-key -T prefix j select-pane -D
bind-key -T prefix k select-pane -U
bind-key -T prefix l select-pane -R

bind-key -T prefix H split-window -h -b -c "#{pane_current_path}"
bind-key -T prefix J split-window -v -c "#{pane_current_path}"
bind-key -T prefix K split-window -v -b -c "#{pane_current_path}"
bind-key -T prefix L split-window -h -c "#{pane_current_path}"

bind-key -r -T prefix C-h resize-pane -L 1
bind-key -r -T prefix C-j resize-pane -D 1
bind-key -r -T prefix C-k resize-pane -U 1
bind-key -r -T prefix C-l resize-pane -R 1

