#!/usr/bin/env fish
# navigation
alias -s .. "cd .."
alias -s ... "cd ../.."
alias -s .... "cd ../../.."
alias -s ..... "cd ../../../.."
alias -s - "cd -"

# git
alias -s ga "git add"
alias -s gaa "git add --all"
alias -s gb "git branch"
alias -s gba "git branch -a"
alias -s gc "git commit -v"
alias -s gca "git commit -a -v"
alias -s gcm "git commit -m"
alias -s gco "git checkout"
alias -s gcb "git checkout -b"
alias -s gd "git diff"
alias -s gds "git diff --staged"
alias -s gl "git pull"
alias -s gp "git push"
alias -s gst "git status"
alias -s gcl "git clone"
alias -s gr "git remote"
alias -s gra "git remote add"
alias -s grv "git remote -v"
alias -s gpl "git pull"
alias -s gps "git push"
alias -s gpo "git push origin"
alias -s gpf "git push --force"
alias -s gsta "git stash"
alias -s gstp "git stash pop"
alias -s gsts "git stash show --text"

